puts "Welcome to your daily fortune!"
puts "Please type in a number from 1 - 10:"
number = gets.chomp
if number == "1"
  puts "Today is not a good day, best to go back to bed and hide all day!"
elsif number == "2"
  puts "Today is an auspicious day for work, just get to work and things will work out."
elsif number == "3"
  puts "Today watch out for old enemies, they're lurking close by..."
elsif number == "4"
  puts "Today is a good day for romance, start planning a romantic day!"
elsif number == "5"
  puts "Hopefully you didn't make plans with a significant other, future with them looks bleak...."
elsif number == "6"
  puts "Today is a good day to reconnect with someone long lost but not forgotten."
elsif number == "7"
  puts "Today someone will cherish you, be prepared for a nice surprise!!!"
elsif number == "8"
  puts "Today all the stars will align in your favor, good day to buy a lottery ticket!"
elsif number == "9"
  puts "Today is a good day to do some good deeds, need to keep karma at bay."
elsif number == "10"
  puts "Today is a good day to buy any item you've been thinking about!"
else 
  puts "The number you entered is invalid, please try again. Once again, please enter a number from 1 - 10!"
end
